package:
  format-version: "1.0.0"
  name: "audio_apps"
  version: "v3.2.1"
  type: "application"
  status: "production"

  dependencies:
    - name: "audio"
      type: "package"
      version: "v3.6.1"
    - name: "helix_mp3"
      type: "package"
      version: "v1.1.0"
    - name: "xiph_flac"
      type: "package"
      version: "v1.0.0"
