format_version: v1.0
type: UniqueComponent
attributes: {id: audio_codec_wm8904}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_WM8904_I2C}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_wm8904, value: DRV_I2C_0}
  - type: String
    attributes: {id: DRV_WM8904_I2S}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_wm8904, value: DRV_I2S_0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: DRV_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c}
  - type: DirectDependency
    attributes: {id: DRV_I2S}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: a_drv_i2s_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2s}
- type: ElementPosition
  attributes: {x: '621', y: '135', id: audio_codec_wm8904}
