configName: basic_sam_e70_xult_wm8904_i2sc_usb_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: audio;audio_apps;audio_apps_corrupted;bsp;core;csp;Devices;dev_packs;dev_packs_bitbucket;dev_packs_bitb_3_12_0;dev_packs_delete;harmony-services;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.6.98\same70b\atdf\ATSAME70Q21B.atdf
