format_version: v1.0
type: UniqueComponent
attributes: {id: a_i2sc0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: I2SC_MR_IMCKDIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '15'}
  - type: KeyValueSet
    attributes: {id: I2SC_MR_IMCKFS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '9'}
  - type: KeyValueSet
    attributes: {id: I2SC_MR_IMCKMODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: I2SC_MR_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '61', y: '322', id: a_i2sc0}
