configName: sam_g55_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../..
processor: ATSAMG55J19
projectName: ''
settings:
  PackageFilter: audio;audio_apps;bsp;core;csp;Devices;dev_packs;harmony-services;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.5.65\samg55\atdf\ATSAMG55J19.atdf
