configName: us_basic_pic32mz_ef_c2_ak4954
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: audio;audio_apps;bsp;bt;core;crypto;cryptoauthlib_apps;csp;gfx;tflite;usb;xiph_flac;xiph_opus;xiph_speex
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
