configName: apb_sam_e54_ult_wm8904_ssc_sdmmc_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: audio;audio_apps;audio_original;bsp;core;csp;dev_packs;gfx;quick_docs;touch;usb;usb_older
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.6.95\atdf\ATSAME54P20A.atdf
