configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: aerospace;audio;audio,currentdecoderdev.100120;audio-previous decoder
    work;audio-with release notes;audio.030921;audio.051121;audio.052721;audio.100920;audio.afternewswitches;audio.b4newswitches;audio.beforeregen.030921;audio.currentdevwnewswitches;audio.fromrepo.081320;audio.latestfromrepo,newswitches;audio.latestfromrepo,oldswitches;audio.newdoc;audio_apps;audio_apps
    - Copy;audio_apps-old;aws_cloud;bootloader;bsp;bt;bt-last with L11 apps!!;bt.030420.withBM83stuff;bt.061620;bt.081221;bt.current;bt.newdoc;bt_apps;classb_sam_e5x_d5x;core;core_apps_sam_c20_c21;core_apps_sam_d5x_e5x;core_apps_sam_g55;crypto;cryptoauthlib;csp;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;diag_periph_c20_c21_src;diag_poc;gfx;gfx_apps;net;periph_diagnostic;quick_docs;reference_apps;touch;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.5.82\samv71b\atdf\ATSAMV71Q21B.atdf
