format_version: v1.0
type: UniqueComponent
attributes: {id: Math}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: LIB_DSP_DSP_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_DSP_LIB_DSP_MIPS32_MZ_EF_NFO3_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '640', y: '20', id: Math}
