format_version: v1.0
type: UniqueComponent
attributes: {id: audio_decoders}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CONFIG_USE_ADPCM_STREAMING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CONFIG_USE_FLAC_DECODER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CONFIG_USE_MP3_DECODER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: LIB_ADPCM_ADPCM_DEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_ADPCM_ADPCM_DEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_FLAC_FLAC_DEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_FLAC_FLAC_DEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_MP3DEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_MP3TABS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_PUB_MP3COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_PUB_MP3DEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_PUB_MPADECOBJFIXPT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_PUB_STATNAME_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_ASSEMBLY_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_BITSTREAM_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_BUFFERS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_CODER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_DCT32_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_DEQUANT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_DQCHAN_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_HUFFMAN_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_HUFFTABS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_IMDCT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_POLYPHASE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_SCALFACT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_STPROC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_SUBBAND_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_HELIX_MP3_FIXPNT_REAL_TRIGTABS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_ID3_ID3_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_ID3_ID3_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_ID3_UTILS_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_ID3_UTILS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_MP3_DEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_MP3_MP3_DEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_ASSERT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_CONFIG_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_EXPORT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_FORMAT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_ORDINALS_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_FLAC_STREAM_DECODER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_SHARE_ALLOC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_SHARE_COMPAT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_INCLUDE_SHARE_ENDSWAP_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_BITMATH_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_BITREADER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_CPU_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_CRC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_FIXED_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_FLOAT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_FORMAT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_BITMATH_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_BITREADER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_CPU_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_CRC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_FIXED_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_FLOAT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_FORMAT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_LPC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_MACROS_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_MD5_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_MEMORY_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_OGG_DECODER_ASPECT_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_OGG_OGG_CONFIG_TYPES_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_OGG_OGG_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PRIVATE_OGG_OS_TYPES_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_INCLUDE_PROTECTED_STREAM_DECODER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_LPC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_MD5_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_MEMORY_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: LIB_XIPH_FLAC_FLAC_MASTER_SRC_LIBFLAC_STREAM_DECODER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '591', y: '161', id: audio_decoders}
